### PR TITLE
Loosen dependencies

### PR DESCRIPTION
**Pull request by greg0ire**
This is a lazy way to know if tests pass or do not pass with guzzle 5 (using travis)

### CODE REVIEW

**Comment by stof** [comment]
Your new requirement is exactly the same than the old one (the ``~`` operator never allows bumping the major version)

**Comment by greg0ire** [comment]
Woops, sorry to hear that. I'm making a dummy commit just to run the tests.

**Comment by greg0ire** [comment]
Ok, it passes, I'm going to try and do that properly

**Comment by greg0ire** [comment]
I had to run `composer self-update` on travis to be able to use a hyphen range.

**Comment by stof** [comment]
hmm, the support of hyphen range is not yet 30 days old IIRC, meaning they may not be getting the composer warning about outdated composer.

**Comment by greg0ire** [comment]
[This commit](https://github.com/composer/composer/commit/ebab9db) is 6 weeks old, and [was merged](https://github.com/composer/composer/commit/72a3526) 6 weeks ago too, so I think it is actually ok…

**Comment by greg0ire** [comment]
ping @stof Looks good to you ?

**Comment by nhaarman** [comment]
@stof Can we get this merged?

**Comment by greg0ire** [comment]
Ok. I'll try to remember to never ever again name a branch `test_p_r_do_not_merge`. Thanks!

**Comment by nhaarman** [comment]
Great!

**Pull request merged**
