### PR TITLE
Upgrades.

### PR DESCRIPTION
**Pull request by kevin-lot**
Upgrade to Symfony 4:
- Use Symfony 4 for internal test instead of Silex.
- Use Phpunit 6.5.
- Remove HHVM and PHP versions inferior to 7.1.

Upgrade code.
- Use last Guzzle with PSR7.
- Add interfaces.
- Add abstract class and split code of ApiContext.
- Add "verify" Guzzle option.
- Change base_url option by base_uri to match with Guzzle client option.

### CODE REVIEW

**Comment by kevin-lot** [comment]
@stof What is the future of this extension ?

**Comment by leberknecht** [comment]
Ahoi!
Would love to see this merged, atm this extension requires phpunit 4-5, and if im not mistaken phpunit 5 is EOL?

**Comment by kevin-lot** [comment]
Almost a year later, I don't know if this pull request will be merged.

**Comment by kevin-lot** [comment]
I'm starting to rewrote this extension with:
 - Symfony 4.3 instead of Silex.
 - Symfony HttpClient with Nyholm and Psr18Client implementation.

Here https://github.com/Keyclic/WebApiExtension/tree/enhancement/http-client.

I'm going to try with our internal API to test the results.
Maybe we will upload it to packagist if tests pass.

**Pull request closed without merging**
